/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package boilerplate

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val app = App()
        assertNotNull(app.greeting, "app should have a greeting")
        assertEquals(app.greeting, "Hello World.")
    }
}
